language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
jdk:
  - oraclejdk8
before_install:
  - yes | sdkmanager "platforms;android-27"
script:
  - echo "apixuApiKey=yourApiKey" > gradle.properties
  - ./gradlew build connectedCheck